### ISSUE TITLE
Ending stage with humans and Quaver, sets pause timeout

### ISSUE THREAD

**Issue by Xayanide** [ZPTXDev/Quaver#155]
**Describe the bug**
User manually ended stage makes Quaver disconnect and end the session but sets pause timeout if there is something playing. That is not intended.

**Affected versions**
What versions of Quaver are affected by this bug? (e.g. all versions before 3.0.1, 2.5.1 to 2.6.3, all versions from 1.2.0)
All versions after 2.8.0

**To reproduce**
1. Go to a stage channel.
2. Play any track with Quaver
3. While a track playing, end the stage
> See error on terminal after reproduction steps:
```
$ node main.js
[Quaver] Connected to Discord! Logged in as ThatKid#6969.
[Quaver] Running version 3.3.1-next.2. For help, see https://github.com/ZapSquared/Quaver/issues.
[Quaver] Connected to Lavalink!
[G 906471497231630336 | U 250934589621665793] Processing command play
[G 906471497231630336 | U 250934589621665793] Executing command play
[G 906471497231630336] Starting track
[G 906471497231630336] Setting pause timeout
```

Stage had already been ended and Quaver is no longer in any voice channel.
But, after the time out that was set after ending the stage reaches its limit, Quaver sends a message to the text channel that it disconnected from inactivity.

**Expected behavior**
Quaver is supposed to end the session only, not set a pausetime out after that.
Also make sure nothing else unintended is going on when a stage is ended. Because an ended stage involves disconnection

**Comment by zapteryx** [comment]
issue is still present and not fixed

**Comment by Xayanide** [comment]
Doing console logs, I think the issue lies like this:
```js
// User manually ended the stage
1. Users: Leaving
2. Quaver: Setting pauseTimeout
3. Quaver: Leaving
4. Quaver: Cleaning up
5. Quaver: Sends pauseTimeout embed
6. Quaver: Set the pauseTimeout
```
This happened like an instant, so pauseTimeout is present. Every user leaves before the bot does when a stage gets ended.
