### ISSUE TITLE
Per-guild options for message format

### ISSUE THREAD

**Issue by Xayanide** [ZPTXDev/Quaver#305]
**Describe the feature**
What feature are you proposing?
Context: https://discord.com/channels/906471497231630336/920107978760261663/996222878666215476
Allow each guild to define how the users want their Quaver to send messages.
There will 3 options:
- Only embedded messages
- Only text based messages
- Only text based messages with emojis included

**List the benefits of adding such a feature**
What will you gain from this feature?
- User flexibility

**Is this feature request related to a problem?**
Is there a problem with the current implementation (if any), or is there an issue that would be resolved with this feature?
N/A

**Comment by zapteryx** [comment]
watered this down a bit, i've decided on a different implementation that will work better with Quaver's formatting. 2 options for now playing message, one simple and one detailed.
