### ISSUE TITLE
Disable buttons during select menu interaction

### ISSUE THREAD

**Issue by Xayanide** [ZPTXDev/Quaver#339]
**Describe the feature**
What feature are you proposing?
Buttons briefly disable but not completely, implement something that makes them completely disabled at that timeframe so they're uninteractable.

**List the benefits of adding such a feature**
What will you gain from this feature?
- Aesthetic

**Is this feature request related to a problem?**
Is there a problem with the current implementation (if any), or is there an issue that would be resolved with this feature?
N/A

**Comment by zapteryx** [comment]
i checked 5.0.0 against 8c2342b01daa1706fbfd68099edb09f5d6625830, and it appears that commit did resolve this issue. that commit was later reverted as part of an ephemeral revert here: 73844539f8058d7b9c036d375f040fecd5d8b655, but that commit kept the loading message after the selection, so it seems to still solve the issue. on that note, I'll be closing this issue.
