### ISSUE TITLE
Quaver does not disconnect from being alone while nothing is playing when the user consecutively skips the track and leaves the channel

### ISSUE THREAD

**Issue by Xayanide** [ZPTXDev/Quaver#346]
**Describe the bug**
What isn't working as intended, and what does it affect?
Pause timeout
Affects user experience and functionality
Is not reproducible with low latency.

**Severity**
- [x] Critical
- [ ] High
- [ ] Medium
- [ ] Low

**Affected versions**
What versions are affected by this bug? (e.g. >=3.0.1, 2.5.1-2.6.3, >=1.2.0)
`< 4.0.0-next.2`

**Steps to reproduce**
Steps to reproduce the behavior. (e.g. click on a button, enter a value, etc. and see error)
1. Play any track with Quaver in voice or stage channel
2. Type `/skip` do not enter it yet.
3. Move your cursor to the disconnect button
4. Prepare to enter skip then press the disconnect button.
5. Must be done in quick succession.

**Expected behavior**
What is expected to happen?
Disconnect as everyone left

**Actual behavior**
What actually happens? Attach or add errors or screenshots here as well.
Does not disconnect from the channel.

Issue confirmation:

https://user-images.githubusercontent.com/18362871/179213482-8780fe7a-f045-48d2-85a5-947fe9e0166c.mp4

Related to the pauseTimeout Quartet issues:
#239
#356
#357

**Comment by zapteryx** [comment]
seems intended, the behaviour to be altered would be what Quaver does while it is on "queue empty, leaving in x"

**Comment by Xayanide** [comment]
I still believe that this is an issue. Will reopen if there is a change of mind.
