### ISSUE TITLE
Skipping a track then moving Quaver to another channel consecutively does not trigger disconnection from being alone

### ISSUE THREAD

**Issue by xayanide** [ZPTXDev/Quaver#357]
**Describe the bug**
What isn't working as intended, and what does it affect?
Pause timeout
Affects user experience and functionality
Is not reproducible with low latency.

**Severity**
- [ ] Critical
- [ ] High
- [ ] Medium
- [x] Low

**Affected versions**
What versions are affected by this bug? (e.g. >=3.0.1, 2.5.1-2.6.3, >=1.2.0)
`< 4.0.0-next.2`

**Steps to reproduce**
Steps to reproduce the behavior. (e.g. click on a button, enter a value, etc. and see error)
1. Play any track with Quaver in voice/stage
2. Type `/skip` do not enter it yet.
3. Move your cursor on Quaver at the voice or stage channel in preparation to hold-click it or any way that moves Quaver
4. Prepare to enter skip then quickly move Quaver to another voice or stage channel.
5. Must be done in quick succession.

**Expected behavior**
What is expected to happen?
Disconnect as there was no one in the target channel.

**Actual behavior**
What actually happens? Attach or add errors or screenshots here as well.
Does not disconnect from the channel.

https://user-images.githubusercontent.com/18362871/179397906-1a69aa99-47cb-422a-9862-8f90c90064df.mp4

Related to the pauseTimeout Quartet issues:
#239
#346
#356

**Comment by zapteryx** [comment]
this will eventually be re-looked at when I take a look at voiceStateUpdate handling again
