### ISSUE TITLE
A more reliable solution for Quaver's disappearing activity status

### ISSUE THREAD

**Issue by Xayanide** [ZPTXDev/Quaver#447]
**Describe the bug**
What isn't working as intended, and what does it affect?
Activity status

**Severity**
- [ ] Critical
- [ ] High
- [ ] Medium
- [x] Low

**Affected branches**
- [x] Stable
- [x] Next

**Steps to reproduce**
Steps to reproduce the behavior. (e.g. click on a button, enter a value, etc. and see error)
1. After some uptime, Quaver's status mysteriously disappears.

**Expected behavior**
What is expected to happen?
The activity status should persist and stay as it is.

**Actual behavior**
What actually happens? Attach or add errors or screenshots here as well.
Disappears.

**Comment by Xayanide** [comment]
Left this issue here just in case the "disappearing activity" still persists after Quaver v5.0.0

**Comment by zapteryx** [comment]
https://github.com/discord/discord-api-docs/issues/834

**Comment by zapteryx** [comment]
This issue does persist
