### ISSUE TITLE
Voteskip is not cleared after track ends

### ISSUE THREAD

**Issue by Xayanide** [ZPTXDev/Quaver#458]
**Describe the bug**
What isn't working as intended, and what does it affect?
Affects functionality

**Severity**
- [x] Critical
- [ ] High
- [ ] Medium
- [ ] Low

**Affected branches**
- [x] Stable
- [x] Next

**Steps to reproduce**
Steps to reproduce the behavior. (e.g. click on a button, enter a value, etc. and see error)
1. Get two or more people in a voice channel, one must not be a manager
2. Skip vote
3. Make sure the track ends

**Expected behavior**
What is expected to happen?
Clear the queue's vote skip after a track ends

**Actual behavior**
What actually happens? Attach or add errors or screenshots here as well.
Does not clear the user's vote skips, causing unintended behavior

**Comment by zapteryx** [comment]
Resolved in 173e833ccafcc11c606bd3c85f7cd57c315dceae
