### ISSUE TITLE
Done button instead of clicking away to queue with search command

### ISSUE THREAD

**Issue by Xayanide** [ZPTXDev/Quaver#480]
**Describe the feature**
What feature are you proposing?
https://discord.com/channels/906471497231630336/920107978760261663/1014053711775010857
> ❝kinda like a shopping cart system❞

**Priority**
- [ ] High
- [x] Medium
- [ ] Low

**List the benefits of adding such a feature**
What will you gain from this feature?
N/A

**Is this feature request related to a problem?**
Is there a problem with the current implementation (if any), or is there an issue that would be resolved with this feature?
N/A

**Comment by zapteryx** [comment]
Resolved by #482
