### ISSUE TITLE
Clicking cancel button from search command doesn't clear the timeout and the search state

### ISSUE THREAD

**Issue by Xayanide** [ZPTXDev/Quaver#481]
**Describe the bug**
What isn't working as intended, and what does it affect?
https://github.com/ZPTXDev/Quaver/blob/next/src/components/buttons/clear.js

**Severity**
- [x] Critical
- [ ] High
- [ ] Medium
- [ ] Low

**Affected branches**
- [ ] Stable
- [x] Next

**Steps to reproduce**
Steps to reproduce the behavior. (e.g. click on a button, enter a value, etc. and see error)
1. Search any track with /search
2. Click cancel button

**Expected behavior**
What is expected to happen?
Clear and delete the searchState

**Actual behavior**
What actually happens? Attach or add errors or screenshots here as well.
Stays there until the timeout expires.

**Comment by zapteryx** [comment]
Indirectly resolved by #482
