### ISSUE TITLE
Better way of storing settings after TypeScript transition

### ISSUE THREAD

**Issue by Xayanide** [ZPTXDev/Quaver#531]
**Describe the feature**
What feature are you proposing?
There has to be a better way.

**Priority**
- [ ] High
- [ ] Medium
- [x] Low

**List the benefits of adding such a feature**
What will you gain from this feature?
N/A

**Is this feature request related to a problem?**
Is there a problem with the current implementation (if any), or is there an issue that would be resolved with this feature?
There was a time I lost my settings and now I have to fill them back up again.

**Comment by zapteryx** [comment]
resolved in eb76cd96c6ad074758724ce99427751a89b8a417
